                                <div class="slider-item fl-wrap">
                                    <div class="bg"  data-bg="images/bg/slider/1.jpg"></div>
                                    <div class=""></div>
                                    <div class="hero-section-wrap fl-wrap">
                                        <div class="container">
                                            
                                            
                                        </div>
                                    </div>
                                </div>

                        